version: '3.4'

services:
  
  identity-api:
    image: ${DOCKER_REGISTRY-}identity-api
    build:
      context: .
      dockerfile: Services/Identity/Beth.Identity.Api/Dockerfile

  catalog-api:
    image: ${DOCKER_REGISTRY-}catalog-api
    build:
      context: .
      dockerfile: Services/Catalog/Beth.Catalog.Api/Dockerfile
    depends_on:
      - identity-api
      - catalog-db
        
  catalog-db:
    image: postgres:15.1