version: '3.4'

services:
  identity-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__redisDb=identity-db
      - RabbitMQSettings__Url=rabbitmq
      - RabbitMQSettings__Host=/
      - RabbitMQSettings__Port=5672
      - RabbitMQSettings__User=guest
      - RabbitMQSettings__Password=guest
    ports:
      - "5200:80"
        
  catalog-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__catalogDb=Host=catalog-db:5432;Database=catalog_db;Username=postgres;Password=postgres
      - ImagesBaseUrl=${BETH_STORAGE_CATALOG_URL}
    ports:
      - "5201:80"
  
  identity-db:
    ports:
      - "5300:6379"
    volumes:
      - identity-db-data:/data
      
  catalog-db:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5301:5432"
    volumes:
      - catalog-db-data:/var/lib/postgresql/data
        
  rabbitmq:
    ports:
      - "5302:15672"
      - "5303:5672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  identity-db-data:
  catalog-db-data:
  rabbitmq-data: