version: '3.4'

services:
  identity-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__redisDb=identity-db
      - RabbitMQSettings__Url=rabbitmq
      - RabbitMQSettings__Host=/
      - RabbitMQSettings__Port=5672
      - RabbitMQSettings__User=guest
      - RabbitMQSettings__Password=guest
  
  catalog-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__catalogDb=Host=catalog-db:5432;Database=catalog_db;Username=postgres;Password=postgres
      - ImagesBaseUrl=${BETH_STORAGE_CATALOG_URL}
  
  catalog-db:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres