version: '3.4'

services:
  
  identity-api:
    image: ${DOCKER_REGISTRY-}identity-api
    build:
      context: .
      dockerfile: Services/Identity/Beth.Identity.Api/Dockerfile
    depends_on:
      - identity-db

  catalog-api:
    image: ${DOCKER_REGISTRY-}catalog-api
    build:
      context: .
      dockerfile: Services/Catalog/Beth.Catalog.Api/Dockerfile
    depends_on:
      - identity-api
      - catalog-db
  
  identity-db:
    image: redis:7.0.5
        
  catalog-db:
    image: postgres:15.1